create table public.django_migrations
(
    id      bigint generated by default as identity primary key,
    app     varchar(255)             not null,
    name    varchar(255)             not null,
    applied timestamp with time zone not null
);

alter table public.django_migrations
    owner to asdf;

create table public."CyberRange_RESTAPI_bibliography"
(
    id   uuid          not null primary key,
    name varchar(255)  not null,
    url  varchar(1000) not null
);

alter table public."CyberRange_RESTAPI_bibliography"
    owner to asdf;

create index "CyberRange__id_d4d63f_idx"
    on public."CyberRange_RESTAPI_bibliography" (id);

create table public."CyberRange_RESTAPI_crevent"
(
    id                 uuid          not null primary key,
    name               varchar(255)  not null,
    points             integer       not null,
    "eventType"        varchar(255)  not null,
    "eventText"        text          not null,
    "questionType"     varchar(255)  not null,
    "trainingMaterial" varchar(2000) not null,
    "materialTitle"    varchar(100)  not null,
    transcript         varchar(2000),
    pool               jsonb         not null,
    feedback           jsonb         not null,
    "partialPoints"    jsonb         not null,
    titles             jsonb         not null,
    phase              varchar(255)  not null,
    view               varchar(255)  not null,
    used               boolean       not null,
    strict             boolean       not null,
    "parentEvent_id"   uuid
        constraint "CyberRange_RESTAPI_c_parentEvent_id_20ebe1df_fk_CyberRang"
            references public."CyberRange_RESTAPI_crevent"
            deferrable initially deferred
);

alter table public."CyberRange_RESTAPI_crevent"
    owner to asdf;

create index "CyberRange__id_a8ae0b_idx"
    on public."CyberRange_RESTAPI_crevent" (id);

create index "CyberRange_RESTAPI_crevent_parentEvent_id_20ebe1df"
    on public."CyberRange_RESTAPI_crevent" ("parentEvent_id");

create table public."CyberRange_RESTAPI_cve"
(
    id             uuid         not null primary key,
    value          varchar(255) not null,
    url            varchar(200) not null,
    description    text         not null,
    "baseSeverity" varchar(20)  not null
);

alter table public."CyberRange_RESTAPI_cve"
    owner to asdf;

create index "CyberRange__id_ee6064_idx"
    on public."CyberRange_RESTAPI_cve" (id);

create table public."CyberRange_RESTAPI_cwe"
(
    id          uuid         not null primary key,
    value       varchar(10)  not null,
    description text         not null,
    url         varchar(200) not null
);

alter table public."CyberRange_RESTAPI_cwe"
    owner to asdf;

create index "CyberRange__id_b41429_idx"
    on public."CyberRange_RESTAPI_cwe" (id);

create table public."CyberRange_RESTAPI_difficulty"
(
    id    uuid         not null primary key,
    level varchar(255) not null
);

alter table public."CyberRange_RESTAPI_difficulty"
    owner to asdf;

create index "CyberRange__id_29d196_idx"
    on public."CyberRange_RESTAPI_difficulty" (id);

create table public."CyberRange_RESTAPI_mitretactic"
(
    id          uuid         not null primary key,
    value       varchar(255) not null
        unique,
    name        text         not null,
    url         varchar(200) not null,
    description text         not null
);

alter table public."CyberRange_RESTAPI_mitretactic"
    owner to asdf;

create index "CyberRange__id_8a2530_idx"
    on public."CyberRange_RESTAPI_mitretactic" (id);

create index "CyberRange_RESTAPI_mitretactic_value_f6000ec9_like"
    on public."CyberRange_RESTAPI_mitretactic" (value varchar_pattern_ops);

create table public."CyberRange_RESTAPI_mitretechnique"
(
    id          uuid         not null primary key,
    value       varchar(255) not null
        unique,
    name        text         not null,
    url         varchar(200) not null,
    description text         not null
);

alter table public."CyberRange_RESTAPI_mitretechnique"
    owner to asdf;

create index "CyberRange__id_fadeeb_idx"
    on public."CyberRange_RESTAPI_mitretechnique" (id);

create index "CyberRange_RESTAPI_mitretechnique_value_72c71edd_like"
    on public."CyberRange_RESTAPI_mitretechnique" (value varchar_pattern_ops);

create table public."CyberRange_RESTAPI_progressioninstance"
(
    id                       uuid    not null primary key,
    "assessmentQuestionsSum" integer not null
);

alter table public."CyberRange_RESTAPI_progressioninstance"
    owner to asdf;

create index "CyberRange__id_c3bc01_idx"
    on public."CyberRange_RESTAPI_progressioninstance" (id);

create table public."CyberRange_RESTAPI_review"
(
    id           uuid          not null primary key,
    rating       integer       not null,
    "maxRating"  integer       not null,
    "reviewText" varchar(1000) not null,
    "submitDate" timestamp with time zone
);

alter table public."CyberRange_RESTAPI_review"
    owner to asdf;

create index "CyberRange__id_1f5bdf_idx"
    on public."CyberRange_RESTAPI_review" (id);

create table public."CyberRange_RESTAPI_role"
(
    id          uuid         not null primary key,
    name        varchar(255) not null,
    value       varchar(255) not null,
    description text         not null,
    framework   varchar(255) not null
);

alter table public."CyberRange_RESTAPI_role"
    owner to asdf;

create index "CyberRange__id_b05344_idx"
    on public."CyberRange_RESTAPI_role" (id);

create table public."CyberRange_RESTAPI_scenario"
(
    id              uuid         not null primary key,
    name            varchar(255) not null,
    description     text         not null,
    goal            text         not null,
    "successRate"   integer      not null,
    duration        integer      not null,
    "validFrom"     timestamp with time zone,
    "validUntil"    timestamp with time zone,
    status          varchar(50)  not null,
    "isInteractive" boolean      not null,
    "isAssessment"  boolean      not null,
    revision        varchar(255) not null,
    difficulty_id   uuid         not null
        constraint "CyberRange_RESTAPI_s_difficulty_id_bebea7f4_fk_CyberRang"
            references public."CyberRange_RESTAPI_difficulty"
            deferrable initially deferred
);

alter table public."CyberRange_RESTAPI_scenario"
    owner to asdf;

create table public."CyberRange_RESTAPI_assignedscenario"
(
    id          uuid not null primary key,
    "dueDate"   timestamp with time zone,
    scenario_id uuid not null
        constraint "CyberRange_RESTAPI_a_scenario_id_02847723_fk_CyberRang"
            references public."CyberRange_RESTAPI_scenario"
            deferrable initially deferred
);

alter table public."CyberRange_RESTAPI_assignedscenario"
    owner to asdf;

create index "CyberRange__id_f0da9b_idx"
    on public."CyberRange_RESTAPI_assignedscenario" (id);

create index "CyberRange_RESTAPI_assignedscenario_scenario_id_02847723"
    on public."CyberRange_RESTAPI_assignedscenario" (scenario_id);

create table public."CyberRange_RESTAPI_programme"
(
    id                        uuid        not null primary key,
    name                      varchar(50) not null
        unique,
    summary                   text        not null,
    "estimatedCompletionTime" bigint      not null,
    status                    varchar(50) not null,
    "validFrom"               timestamp with time zone,
    "validUntil"              timestamp with time zone,
    assessment_id             uuid
        unique
        constraint "CyberRange_RESTAPI_p_assessment_id_97fb3fe6_fk_CyberRang"
            references public."CyberRange_RESTAPI_scenario"
            deferrable initially deferred,
    difficulty_id             uuid        not null
        constraint "CyberRange_RESTAPI_p_difficulty_id_6a85c60f_fk_CyberRang"
            references public."CyberRange_RESTAPI_difficulty"
            deferrable initially deferred,
    "updatedProgramme_id"     uuid
        unique
        constraint "CyberRange_RESTAPI_p_updatedProgramme_id_ec0169ed_fk_CyberRang"
            references public."CyberRange_RESTAPI_programme"
            deferrable initially deferred
);

alter table public."CyberRange_RESTAPI_programme"
    owner to asdf;

create index "CyberRange__id_b29a93_idx"
    on public."CyberRange_RESTAPI_programme" (id);

create index "CyberRange_RESTAPI_programme_name_609158bd_like"
    on public."CyberRange_RESTAPI_programme" (name varchar_pattern_ops);

create index "CyberRange_RESTAPI_programme_difficulty_id_6a85c60f"
    on public."CyberRange_RESTAPI_programme" (difficulty_id);

create index "CyberRange__id_c4600d_idx"
    on public."CyberRange_RESTAPI_scenario" (id);

create index "CyberRange_RESTAPI_scenario_difficulty_id_bebea7f4"
    on public."CyberRange_RESTAPI_scenario" (difficulty_id);

create table public."CyberRange_RESTAPI_scenario_bibliography"
(
    id              bigint generated by default as identity primary key,
    scenario_id     uuid not null
        constraint "CyberRange_RESTAPI_s_scenario_id_c62f6283_fk_CyberRang"
            references public."CyberRange_RESTAPI_scenario"
            deferrable initially deferred,
    bibliography_id uuid not null
        constraint "CyberRange_RESTAPI_s_bibliography_id_a1406ddf_fk_CyberRang"
            references public."CyberRange_RESTAPI_bibliography"
            deferrable initially deferred,
    constraint "CyberRange_RESTAPI_scena_scenario_id_bibliography_bbb44126_uniq"
        unique (scenario_id, bibliography_id)
);

alter table public."CyberRange_RESTAPI_scenario_bibliography"
    owner to asdf;

create index "CyberRange_RESTAPI_scenario_bibliography_scenario_id_c62f6283"
    on public."CyberRange_RESTAPI_scenario_bibliography" (scenario_id);

create index "CyberRange_RESTAPI_scenari_bibliography_id_a1406ddf"
    on public."CyberRange_RESTAPI_scenario_bibliography" (bibliography_id);

create table public."CyberRange_RESTAPI_scenario_cves"
(
    id          bigint generated by default as identity primary key,
    scenario_id uuid not null
        constraint "CyberRange_RESTAPI_s_scenario_id_2e4bde77_fk_CyberRang"
            references public."CyberRange_RESTAPI_scenario"
            deferrable initially deferred,
    cve_id      uuid not null
        constraint "CyberRange_RESTAPI_s_cve_id_ea0ea921_fk_CyberRang"
            references public."CyberRange_RESTAPI_cve"
            deferrable initially deferred,
    constraint "CyberRange_RESTAPI_scena_scenario_id_cve_id_c98494d8_uniq"
        unique (scenario_id, cve_id)
);

alter table public."CyberRange_RESTAPI_scenario_cves"
    owner to asdf;

create index "CyberRange_RESTAPI_scenario_cves_scenario_id_2e4bde77"
    on public."CyberRange_RESTAPI_scenario_cves" (scenario_id);

create index "CyberRange_RESTAPI_scenario_cves_cve_id_ea0ea921"
    on public."CyberRange_RESTAPI_scenario_cves" (cve_id);

create table public."CyberRange_RESTAPI_scenario_cwes"
(
    id          bigint generated by default as identity primary key,
    scenario_id uuid not null
        constraint "CyberRange_RESTAPI_s_scenario_id_63f33f95_fk_CyberRang"
            references public."CyberRange_RESTAPI_scenario"
            deferrable initially deferred,
    cwe_id      uuid not null
        constraint "CyberRange_RESTAPI_s_cwe_id_017925e9_fk_CyberRang"
            references public."CyberRange_RESTAPI_cwe"
            deferrable initially deferred,
    constraint "CyberRange_RESTAPI_scena_scenario_id_cwe_id_54fc14c2_uniq"
        unique (scenario_id, cwe_id)
);

alter table public."CyberRange_RESTAPI_scenario_cwes"
    owner to asdf;

create index "CyberRange_RESTAPI_scenario_cwes_scenario_id_63f33f95"
    on public."CyberRange_RESTAPI_scenario_cwes" (scenario_id);

create index "CyberRange_RESTAPI_scenario_cwes_cwe_id_017925e9"
    on public."CyberRange_RESTAPI_scenario_cwes" (cwe_id);

create table public."CyberRange_RESTAPI_scenario_mitreTactics"
(
    id             bigint generated by default as identity primary key,
    scenario_id    uuid not null
        constraint "CyberRange_RESTAPI_s_scenario_id_89f8bf56_fk_CyberRang"
            references public."CyberRange_RESTAPI_scenario"
            deferrable initially deferred,
    mitretactic_id uuid not null
        constraint "CyberRange_RESTAPI_s_mitretactic_id_3ce1c4ad_fk_CyberRang"
            references public."CyberRange_RESTAPI_mitretactic"
            deferrable initially deferred,
    constraint "CyberRange_RESTAPI_scena_scenario_id_mitretactic__0a90cf53_uniq"
        unique (scenario_id, mitretactic_id)
);

alter table public."CyberRange_RESTAPI_scenario_mitreTactics"
    owner to asdf;

create index "CyberRange_RESTAPI_scenario_mitreTactics_scenario_id_89f8bf56"
    on public."CyberRange_RESTAPI_scenario_mitreTactics" (scenario_id);

create index "CyberRange_RESTAPI_scenari_mitretactic_id_3ce1c4ad"
    on public."CyberRange_RESTAPI_scenario_mitreTactics" (mitretactic_id);

create table public."CyberRange_RESTAPI_scenario_mitreTechniques"
(
    id                bigint generated by default as identity primary key,
    scenario_id       uuid not null
        constraint "CyberRange_RESTAPI_s_scenario_id_c3580b82_fk_CyberRang"
            references public."CyberRange_RESTAPI_scenario"
            deferrable initially deferred,
    mitretechnique_id uuid not null
        constraint "CyberRange_RESTAPI_s_mitretechnique_id_17a95822_fk_CyberRang"
            references public."CyberRange_RESTAPI_mitretechnique"
            deferrable initially deferred,
    constraint "CyberRange_RESTAPI_scena_scenario_id_mitretechniq_4002d82c_uniq"
        unique (scenario_id, mitretechnique_id)
);

alter table public."CyberRange_RESTAPI_scenario_mitreTechniques"
    owner to asdf;

create index "CyberRange_RESTAPI_scenari_scenario_id_c3580b82"
    on public."CyberRange_RESTAPI_scenario_mitreTechniques" (scenario_id);

create index "CyberRange_RESTAPI_scenari_mitretechnique_id_17a95822"
    on public."CyberRange_RESTAPI_scenario_mitreTechniques" (mitretechnique_id);

create table public."CyberRange_RESTAPI_scenario_role"
(
    id          bigint generated by default as identity primary key,
    scenario_id uuid not null
        constraint "CyberRange_RESTAPI_s_scenario_id_fb26c473_fk_CyberRang"
            references public."CyberRange_RESTAPI_scenario"
            deferrable initially deferred,
    role_id     uuid not null
        constraint "CyberRange_RESTAPI_s_role_id_048121b4_fk_CyberRang"
            references public."CyberRange_RESTAPI_role"
            deferrable initially deferred,
    constraint "CyberRange_RESTAPI_scena_scenario_id_role_id_404faa95_uniq"
        unique (scenario_id, role_id)
);

alter table public."CyberRange_RESTAPI_scenario_role"
    owner to asdf;

create index "CyberRange_RESTAPI_scenario_role_scenario_id_fb26c473"
    on public."CyberRange_RESTAPI_scenario_role" (scenario_id);

create index "CyberRange_RESTAPI_scenario_role_role_id_048121b4"
    on public."CyberRange_RESTAPI_scenario_role" (role_id);

create table public."CyberRange_RESTAPI_state"
(
    id                     uuid        not null primary key,
    name                   varchar(20) not null,
    progress               integer     not null,
    layout                 varchar     not null,
    "isPreAssesment"       boolean     not null,
    "startState"           boolean     not null,
    "assessmentStartState" boolean     not null
);

alter table public."CyberRange_RESTAPI_state"
    owner to asdf;

create index "CyberRange__id_d173ff_idx"
    on public."CyberRange_RESTAPI_state" (id);

create table public."CyberRange_RESTAPI_state_onEnterEvent"
(
    id         bigint generated by default as identity primary key,
    state_id   uuid not null
        constraint "CyberRange_RESTAPI_s_state_id_8c78f5c6_fk_CyberRang"
            references public."CyberRange_RESTAPI_state"
            deferrable initially deferred,
    crevent_id uuid not null
        constraint "CyberRange_RESTAPI_s_crevent_id_05877c79_fk_CyberRang"
            references public."CyberRange_RESTAPI_crevent"
            deferrable initially deferred,
    constraint "CyberRange_RESTAPI_state_state_id_crevent_id_34d766b3_uniq"
        unique (state_id, crevent_id)
);

alter table public."CyberRange_RESTAPI_state_onEnterEvent"
    owner to asdf;

create index "CyberRange_RESTAPI_state_onEnterEvent_state_id_8c78f5c6"
    on public."CyberRange_RESTAPI_state_onEnterEvent" (state_id);

create index "CyberRange_RESTAPI_state_onEnterEvent_crevent_id_05877c79"
    on public."CyberRange_RESTAPI_state_onEnterEvent" (crevent_id);

create table public."CyberRange_RESTAPI_state_onExitEvent"
(
    id         bigint generated by default as identity primary key,
    state_id   uuid not null
        constraint "CyberRange_RESTAPI_s_state_id_411db74d_fk_CyberRang"
            references public."CyberRange_RESTAPI_state"
            deferrable initially deferred,
    crevent_id uuid not null
        constraint "CyberRange_RESTAPI_s_crevent_id_eeb5a20f_fk_CyberRang"
            references public."CyberRange_RESTAPI_crevent"
            deferrable initially deferred,
    constraint "CyberRange_RESTAPI_state_state_id_crevent_id_a432f34a_uniq"
        unique (state_id, crevent_id)
);

alter table public."CyberRange_RESTAPI_state_onExitEvent"
    owner to asdf;

create index "CyberRange_RESTAPI_state_onExitEvent_state_id_411db74d"
    on public."CyberRange_RESTAPI_state_onExitEvent" (state_id);

create index "CyberRange_RESTAPI_state_onExitEvent_crevent_id_eeb5a20f"
    on public."CyberRange_RESTAPI_state_onExitEvent" (crevent_id);

create table public."CyberRange_RESTAPI_usermetadata"
(
    id       uuid        not null primary key,
    username varchar(50) not null,
    "orgId"  varchar(50) not null,
    roles    jsonb       not null
);

alter table public."CyberRange_RESTAPI_usermetadata"
    owner to asdf;

create table public."CyberRange_RESTAPI_assignedprogramme"
(
    id                                      uuid                     not null primary key,
    "trainingScenariosCompletionPercentage" double precision         not null,
    "programmeFullyCompleted"               boolean                  not null,
    "programmeDueDate"                      timestamp with time zone,
    "totalTimeSpent"                        integer                  not null,
    "createdAt"                             timestamp with time zone not null,
    assigner_id                             uuid
        constraint "CyberRange_RESTAPI_a_assigner_id_b8fc2b54_fk_CyberRang"
            references public."CyberRange_RESTAPI_usermetadata"
            deferrable initially deferred,
    programme_id                            uuid                     not null
        constraint "CyberRange_RESTAPI_a_programme_id_d4765487_fk_CyberRang"
            references public."CyberRange_RESTAPI_programme"
            deferrable initially deferred
);

alter table public."CyberRange_RESTAPI_assignedprogramme"
    owner to asdf;

create index "CyberRange__id_12256d_idx"
    on public."CyberRange_RESTAPI_assignedprogramme" (id);

create index "CyberRange_RESTAPI_assignedprogramme_assigner_id_b8fc2b54"
    on public."CyberRange_RESTAPI_assignedprogramme" (assigner_id);

create index "CyberRange_RESTAPI_assignedprogramme_programme_id_d4765487"
    on public."CyberRange_RESTAPI_assignedprogramme" (programme_id);

create table public."CyberRange_RESTAPI_programmetrainer"
(
    id           uuid not null primary key,
    programme_id uuid not null
        constraint "CyberRange_RESTAPI_p_programme_id_7cdb20c7_fk_CyberRang"
            references public."CyberRange_RESTAPI_programme"
            deferrable initially deferred,
    trainer_id   uuid
        constraint "CyberRange_RESTAPI_p_trainer_id_2a48e7e8_fk_CyberRang"
            references public."CyberRange_RESTAPI_usermetadata"
            deferrable initially deferred
);

alter table public."CyberRange_RESTAPI_programmetrainer"
    owner to asdf;

create index "CyberRange__id_90ba29_idx"
    on public."CyberRange_RESTAPI_programmetrainer" (id);

create index "CyberRange_RESTAPI_programmetrainer_programme_id_7cdb20c7"
    on public."CyberRange_RESTAPI_programmetrainer" (programme_id);

create index "CyberRange_RESTAPI_programmetrainer_trainer_id_2a48e7e8"
    on public."CyberRange_RESTAPI_programmetrainer" (trainer_id);

create table public."CyberRange_RESTAPI_programmeuserreview"
(
    id               uuid not null primary key,
    programme_id     uuid
        constraint "CyberRange_RESTAPI_p_programme_id_3222e67a_fk_CyberRang"
            references public."CyberRange_RESTAPI_programme"
            deferrable initially deferred,
    review_id        uuid
        constraint "CyberRange_RESTAPI_p_review_id_1bc2cfcf_fk_CyberRang"
            references public."CyberRange_RESTAPI_review"
            deferrable initially deferred,
    user_metadata_id uuid
        constraint "CyberRange_RESTAPI_p_user_metadata_id_51a1a3e0_fk_CyberRang"
            references public."CyberRange_RESTAPI_usermetadata"
            deferrable initially deferred
);

alter table public."CyberRange_RESTAPI_programmeuserreview"
    owner to asdf;

create index "CyberRange_RESTAPI_programmeuserreview_programme_id_3222e67a"
    on public."CyberRange_RESTAPI_programmeuserreview" (programme_id);

create index "CyberRange_RESTAPI_programmeuserreview_review_id_1bc2cfcf"
    on public."CyberRange_RESTAPI_programmeuserreview" (review_id);

create index "CyberRange_RESTAPI_program_user_metadata_id_51a1a3e0"
    on public."CyberRange_RESTAPI_programmeuserreview" (user_metadata_id);

create index "CyberRange__id_67b4f1_idx"
    on public."CyberRange_RESTAPI_usermetadata" (id);

create table public."CyberRange_RESTAPI_usermetadata_assignedProgrammes"
(
    id                   bigint generated by default as identity primary key,
    usermetadata_id      uuid not null
        constraint "CyberRange_RESTAPI_u_usermetadata_id_274ab3eb_fk_CyberRang"
            references public."CyberRange_RESTAPI_usermetadata"
            deferrable initially deferred,
    assignedprogramme_id uuid not null
        constraint "CyberRange_RESTAPI_u_assignedprogramme_id_f4bbd4a8_fk_CyberRang"
            references public."CyberRange_RESTAPI_assignedprogramme"
            deferrable initially deferred,
    constraint "CyberRange_RESTAPI_userm_usermetadata_id_assigned_c5b7e789_uniq"
        unique (usermetadata_id, assignedprogramme_id)
);

alter table public."CyberRange_RESTAPI_usermetadata_assignedProgrammes"
    owner to asdf;

create index "CyberRange_RESTAPI_usermet_usermetadata_id_274ab3eb"
    on public."CyberRange_RESTAPI_usermetadata_assignedProgrammes" (usermetadata_id);

create index "CyberRange_RESTAPI_usermet_assignedprogramme_id_f4bbd4a8"
    on public."CyberRange_RESTAPI_usermetadata_assignedProgrammes" (assignedprogramme_id);

create table public."CyberRange_RESTAPI_usermetadata_assignedScenarios"
(
    id                  bigint generated by default as identity primary key,
    usermetadata_id     uuid not null
        constraint "CyberRange_RESTAPI_u_usermetadata_id_8a94e2bb_fk_CyberRang"
            references public."CyberRange_RESTAPI_usermetadata"
            deferrable initially deferred,
    assignedscenario_id uuid not null
        constraint "CyberRange_RESTAPI_u_assignedscenario_id_d014b79f_fk_CyberRang"
            references public."CyberRange_RESTAPI_assignedscenario"
            deferrable initially deferred,
    constraint "CyberRange_RESTAPI_userm_usermetadata_id_assigned_5179f769_uniq"
        unique (usermetadata_id, assignedscenario_id)
);

alter table public."CyberRange_RESTAPI_usermetadata_assignedScenarios"
    owner to asdf;

create index "CyberRange_RESTAPI_usermet_usermetadata_id_8a94e2bb"
    on public."CyberRange_RESTAPI_usermetadata_assignedScenarios" (usermetadata_id);

create index "CyberRange_RESTAPI_usermet_assignedscenario_id_d014b79f"
    on public."CyberRange_RESTAPI_usermetadata_assignedScenarios" (assignedscenario_id);

create table public."CyberRange_RESTAPI_usermetadata_createdProgrammes"
(
    id              bigint generated by default as identity primary key,
    usermetadata_id uuid not null
        constraint "CyberRange_RESTAPI_u_usermetadata_id_eb76c25b_fk_CyberRang"
            references public."CyberRange_RESTAPI_usermetadata"
            deferrable initially deferred,
    programme_id    uuid not null
        constraint "CyberRange_RESTAPI_u_programme_id_d15b495c_fk_CyberRang"
            references public."CyberRange_RESTAPI_programme"
            deferrable initially deferred,
    constraint "CyberRange_RESTAPI_userm_usermetadata_id_programm_044e2cd1_uniq"
        unique (usermetadata_id, programme_id)
);

alter table public."CyberRange_RESTAPI_usermetadata_createdProgrammes"
    owner to asdf;

create index "CyberRange_RESTAPI_usermet_usermetadata_id_eb76c25b"
    on public."CyberRange_RESTAPI_usermetadata_createdProgrammes" (usermetadata_id);

create index "CyberRange_RESTAPI_usermet_programme_id_d15b495c"
    on public."CyberRange_RESTAPI_usermetadata_createdProgrammes" (programme_id);

create table public."CyberRange_RESTAPI_usermetadata_createdScenarios"
(
    id              bigint generated by default as identity primary key,
    usermetadata_id uuid not null
        constraint "CyberRange_RESTAPI_u_usermetadata_id_2ae93fdd_fk_CyberRang"
            references public."CyberRange_RESTAPI_usermetadata"
            deferrable initially deferred,
    scenario_id     uuid not null
        constraint "CyberRange_RESTAPI_u_scenario_id_b80a072d_fk_CyberRang"
            references public."CyberRange_RESTAPI_scenario"
            deferrable initially deferred,
    constraint "CyberRange_RESTAPI_userm_usermetadata_id_scenario_154f0c10_uniq"
        unique (usermetadata_id, scenario_id)
);

alter table public."CyberRange_RESTAPI_usermetadata_createdScenarios"
    owner to asdf;

create index "CyberRange_RESTAPI_usermet_usermetadata_id_2ae93fdd"
    on public."CyberRange_RESTAPI_usermetadata_createdScenarios" (usermetadata_id);

create index "CyberRange_RESTAPI_usermet_scenario_id_b80a072d"
    on public."CyberRange_RESTAPI_usermetadata_createdScenarios" (scenario_id);

create table public."CyberRange_RESTAPI_usermetadata_reviews"
(
    id              bigint generated by default as identity primary key,
    usermetadata_id uuid not null
        constraint "CyberRange_RESTAPI_u_usermetadata_id_5c08cd8b_fk_CyberRang"
            references public."CyberRange_RESTAPI_usermetadata"
            deferrable initially deferred,
    review_id       uuid not null
        constraint "CyberRange_RESTAPI_u_review_id_5cd4054d_fk_CyberRang"
            references public."CyberRange_RESTAPI_review"
            deferrable initially deferred,
    constraint "CyberRange_RESTAPI_userm_usermetadata_id_review_i_7824c75c_uniq"
        unique (usermetadata_id, review_id)
);

alter table public."CyberRange_RESTAPI_usermetadata_reviews"
    owner to asdf;

create index "CyberRange_RESTAPI_usermet_usermetadata_id_5c08cd8b"
    on public."CyberRange_RESTAPI_usermetadata_reviews" (usermetadata_id);

create index "CyberRange_RESTAPI_usermetadata_reviews_review_id_5cd4054d"
    on public."CyberRange_RESTAPI_usermetadata_reviews" (review_id);

create table public."CyberRange_RESTAPI_usertrainingtime"
(
    id                       uuid    not null primary key,
    date                     date    not null,
    "totalTime"              integer not null,
    "programmeAssignment_id" uuid    not null
        constraint "CyberRange_RESTAPI_u_programmeAssignment__58b35d00_fk_CyberRang"
            references public."CyberRange_RESTAPI_assignedprogramme"
            deferrable initially deferred,
    user_id                  uuid    not null
        constraint "CyberRange_RESTAPI_u_user_id_1f56c7cc_fk_CyberRang"
            references public."CyberRange_RESTAPI_usermetadata"
            deferrable initially deferred,
    constraint "CyberRange_RESTAPI_usert_user_id_date_programmeAs_d53935f6_uniq"
        unique (user_id, date, "programmeAssignment_id")
);

alter table public."CyberRange_RESTAPI_usertrainingtime"
    owner to asdf;

create index "CyberRange__id_459d53_idx"
    on public."CyberRange_RESTAPI_usertrainingtime" (id, date);

create index "CyberRange_RESTAPI_usertra_programmeAssignment_id_58b35d00"
    on public."CyberRange_RESTAPI_usertrainingtime" ("programmeAssignment_id");

create index "CyberRange_RESTAPI_usertrainingtime_user_id_1f56c7cc"
    on public."CyberRange_RESTAPI_usertrainingtime" (user_id);

create table public."CyberRange_RESTAPI_transition"
(
    id                 uuid             not null primary key,
    name               varchar(100)     not null,
    probability        double precision not null,
    "sourceState_id"   uuid             not null
        constraint "CyberRange_RESTAPI_t_sourceState_id_7aa18af3_fk_CyberRang"
            references public."CyberRange_RESTAPI_state"
            deferrable initially deferred,
    "targetState_id"   uuid             not null
        constraint "CyberRange_RESTAPI_t_targetState_id_4c0dc26e_fk_CyberRang"
            references public."CyberRange_RESTAPI_state"
            deferrable initially deferred,
    "triggerAction_id" uuid             not null
        constraint "CyberRange_RESTAPI_t_triggerAction_id_fe4e4953_fk_CyberRang"
            references public."CyberRange_RESTAPI_crevent"
            deferrable initially deferred
);

alter table public."CyberRange_RESTAPI_transition"
    owner to asdf;

create index "CyberRange__id_9fb75c_idx"
    on public."CyberRange_RESTAPI_transition" (id);

create index "CyberRange_RESTAPI_transition_sourceState_id_7aa18af3"
    on public."CyberRange_RESTAPI_transition" ("sourceState_id");

create index "CyberRange_RESTAPI_transition_targetState_id_4c0dc26e"
    on public."CyberRange_RESTAPI_transition" ("targetState_id");

create index "CyberRange_RESTAPI_transition_triggerAction_id_fe4e4953"
    on public."CyberRange_RESTAPI_transition" ("triggerAction_id");

create table public."CyberRange_RESTAPI_trainingtype"
(
    id    uuid         not null primary key,
    value varchar(255) not null
);

alter table public."CyberRange_RESTAPI_trainingtype"
    owner to asdf;

create index "CyberRange__id_9cfefb_idx"
    on public."CyberRange_RESTAPI_trainingtype" (id);

create table public."CyberRange_RESTAPI_statemachine"
(
    id              uuid    not null primary key,
    "lazyLoad"      boolean not null,
    name            text    not null,
    "scenarioId_id" uuid    not null
        constraint "CyberRange_RESTAPI_s_scenarioId_id_9a7c2160_fk_CyberRang"
            references public."CyberRange_RESTAPI_scenario"
            deferrable initially deferred
);

alter table public."CyberRange_RESTAPI_statemachine"
    owner to asdf;

create table public."CyberRange_RESTAPI_instance"
(
    id                          uuid                     not null primary key,
    "currentPoints"             integer                  not null,
    "currentProgress"           integer                  not null,
    status                      varchar(20)              not null,
    "nextAssessmentNumber"      integer                  not null,
    "traineeId"                 varchar(36)              not null,
    "timeLeft"                  integer                  not null,
    "totalPoints"               integer                  not null,
    "reportFilePath"            varchar(255)             not null,
    "taskId"                    varchar(255),
    phase                       varchar(20)              not null,
    graph                       jsonb,
    history                     jsonb,
    "assessmentTimeFingerprint" timestamp with time zone,
    deterministic               varchar(20)              not null,
    "lastSessionStart"          timestamp with time zone,
    "lastSessionEnd"            timestamp with time zone,
    "totalTime"                 integer                  not null,
    "createdAt"                 timestamp with time zone not null,
    "FSMBlueprint_id"           uuid                     not null
        constraint "CyberRange_RESTAPI_i_FSMBlueprint_id_fc774d56_fk_CyberRang"
            references public."CyberRange_RESTAPI_statemachine"
            deferrable initially deferred,
    "lastVisitedState_id"       uuid
        constraint "CyberRange_RESTAPI_i_lastVisitedState_id_6eb4aa55_fk_CyberRang"
            references public."CyberRange_RESTAPI_state"
            deferrable initially deferred,
    "progressionInstance_id"    uuid
        constraint "CyberRange_RESTAPI_i_progressionInstance__9ff3c891_fk_CyberRang"
            references public."CyberRange_RESTAPI_progressioninstance"
            deferrable initially deferred,
    "scenarioId_id"             uuid                     not null
        constraint "CyberRange_RESTAPI_i_scenarioId_id_a9a9a9fb_fk_CyberRang"
            references public."CyberRange_RESTAPI_scenario"
            deferrable initially deferred
);
