create table public.django_migrations
(
    id      bigint generated by default as identity
        primary key,
    app     varchar(255)             not null,
    name    varchar(255)             not null,
    applied timestamp with time zone not null
);

alter table public.django_migrations
    owner to asdf;

create table public."CyberRange_RESTAPI_bibliography"
(
    id   uuid          not null
        primary key,
    name varchar(255)  not null,
    url  varchar(1000) not null
);

alter table public."CyberRange_RESTAPI_bibliography"
    owner to asdf;

create index "CyberRange__id_d4d63f_idx"
    on public."CyberRange_RESTAPI_bibliography" (id);

create table public."CyberRange_RESTAPI_crevent"
(
    id                 uuid          not null
        primary key,
    name               varchar(255)  not null,
    points             integer       not null,
    "eventType"        varchar(255)  not null,
    "eventText"        text          not null,
    "questionType"     varchar(255)  not null,
    "trainingMaterial" varchar(2000) not null,
    "materialTitle"    varchar(100)  not null,
    transcript         varchar(2000),
    pool               jsonb         not null,
    feedback           jsonb         not null,
    "partialPoints"    jsonb         not null,
    titles             jsonb         not null,
    phase              varchar(255)  not null,
    view               varchar(255)  not null,
    used               boolean       not null,
    strict             boolean       not null,
    "parentEvent_id"   uuid
        constraint "CyberRange_RESTAPI_c_parentEvent_id_20ebe1df_fk_CyberRang"
            references public."CyberRange_RESTAPI_crevent"
            deferrable initially deferred
);

alter table public."CyberRange_RESTAPI_crevent"
    owner to asdf;

create index "CyberRange__id_a8ae0b_idx"
    on public."CyberRange_RESTAPI_crevent" (id);

create index "CyberRange_RESTAPI_crevent_parentEvent_id_20ebe1df"
    on public."CyberRange_RESTAPI_crevent" ("parentEvent_id");

create table public."CyberRange_RESTAPI_cve"
(
    id             uuid         not null
        primary key,
    value          varchar(255) not null,
    url            varchar(200) not null,
    description    text         not null,
    "baseSeverity" varchar(20)  not null
);

alter table public."CyberRange_RESTAPI_cve"
    owner to asdf;

create index "CyberRange__id_ee6064_idx"
    on public."CyberRange_RESTAPI_cve" (id);

create table public."CyberRange_RESTAPI_cwe"
(
    id          uuid         not null
        primary key,
    value       varchar(10)  not null,
    description text         not null,
    url         varchar(200) not null
);

alter table public."CyberRange_RESTAPI_cwe"
    owner to asdf;

create index "CyberRange__id_b41429_idx"
    on public."CyberRange_RESTAPI_cwe" (id);

create table public."CyberRange_RESTAPI_difficulty"
(
    id    uuid         not null
        primary key,
    level varchar(255) not null
);

alter table public."CyberRange_RESTAPI_difficulty"
    owner to asdf;

create index "CyberRange__id_29d196_idx"
    on public."CyberRange_RESTAPI_difficulty" (id);

create table public."CyberRange_RESTAPI_mitretactic"
(
    id          uuid         not null
        primary key,
    value       varchar(255) not null
        unique,
    name        text         not null,
    url         varchar(200) not null,
    description text         not null
);

alter table public."CyberRange_RESTAPI_mitretactic"
    owner to asdf;

create index "CyberRange__id_8a2530_idx"
    on public."CyberRange_RESTAPI_mitretactic" (id);

create index "CyberRange_RESTAPI_mitretactic_value_f6000ec9_like"
    on public."CyberRange_RESTAPI_mitretactic" (value varchar_pattern_ops);

create table public."CyberRange_RESTAPI_mitretechnique"
(
    id          uuid         not null
        primary key,
    value       varchar(255) not null
        unique,
    name        text         not null,
    url         varchar(200) not null,
    description text         not null
);

alter table public."CyberRange_RESTAPI_mitretechnique"
    owner to asdf;

create index "CyberRange__id_fadeeb_idx"
    on public."CyberRange_RESTAPI_mitretechnique" (id);

create index "CyberRange_RESTAPI_mitretechnique_value_72c71edd_like"
    on public."CyberRange_RESTAPI_mitretechnique" (value varchar_pattern_ops);

create table public."CyberRange_RESTAPI_progressioninstance"
(
    id                       uuid    not null
        primary key,
    "assessmentQuestionsSum" integer not null
);

alter table public."CyberRange_RESTAPI_progressioninstance"
    owner to asdf;

create index "CyberRange__id_c3bc01_idx"
    on public."CyberRange_RESTAPI_progressioninstance" (id);

create table public."CyberRange_RESTAPI_review"
(
    id           uuid          not null
        primary key,
    rating       integer       not null,
    "maxRating"  integer       not null,
    "reviewText" varchar(1000) not null,
    "submitDate" timestamp with time zone
);

alter table public."CyberRange_RESTAPI_review"
    owner to asdf;

create index "CyberRange__id_1f5bdf_idx"
    on public."CyberRange_RESTAPI_review" (id);

create table public."CyberRange_RESTAPI_role"
(
    id          uuid         not null
        primary key,
    name        varchar(255) not null,
    value       varchar(255) not null,
    description text         not null,
    framework   varchar(255) not null
);

alter table public."CyberRange_RESTAPI_role"
    owner to asdf;

create index "CyberRange__id_b05344_idx"
    on public."CyberRange_RESTAPI_role" (id);

create table public."CyberRange_RESTAPI_scenario"
(
    id              uuid         not null
        primary key,
    name            varchar(255) not null,
    description     text         not null,
    goal            text         not null,
    "successRate"   integer      not null,
    duration        integer      not null,
    "validFrom"     timestamp with time zone,
    "validUntil"    timestamp with time zone,
    status          varchar(50)  not null,
    "isInteractive" boolean      not null,
    "isAssessment"  boolean      not null,
    revision        varchar(255) not null,
    difficulty_id   uuid         not null
        constraint "CyberRange_RESTAPI_s_difficulty_id_bebea7f4_fk_CyberRang"
            references public."CyberRange_RESTAPI_difficulty"
            deferrable initially deferred
);

alter table public."CyberRange_RESTAPI_scenario"
    owner to asdf;

create table public."CyberRange_RESTAPI_assignedscenario"
(
    id          uuid not null
        primary key,
    "dueDate"   timestamp with time zone,
    scenario_id uuid not null
        constraint "CyberRange_RESTAPI_a_scenario_id_02847723_fk_CyberRang"
            references public."CyberRange_RESTAPI_scenario"
            deferrable initially deferred
);

alter table public."CyberRange_RESTAPI_assignedscenario"
    owner to asdf;

create index "CyberRange__id_f0da9b_idx"
    on public."CyberRange_RESTAPI_assignedscenario" (id);

create index "CyberRange_RESTAPI_assignedscenario_scenario_id_02847723"
    on public."CyberRange_RESTAPI_assignedscenario" (scenario_id);

create table public."CyberRange_RESTAPI_programme"
(
    id                        uuid        not null
        primary key,
    name                      varchar(50) not null
        unique,
    summary                   text        not null,
    "estimatedCompletionTime" bigint      not null,
    status                    varchar(50) not null,
    "validFrom"               timestamp with time zone,
    "validUntil"              timestamp with time zone,
    assessment_id             uuid
        unique
        constraint "CyberRange_RESTAPI_p_assessment_id_97fb3fe6_fk_CyberRang"
            references public."CyberRange_RESTAPI_scenario"
            deferrable initially deferred,
    difficulty_id             uuid        not null
        constraint "CyberRange_RESTAPI_p_difficulty_id_6a85c60f_fk_CyberRang"
            references public."CyberRange_RESTAPI_difficulty"
            deferrable initially deferred,
    "updatedProgramme_id"     uuid
        unique
        constraint "CyberRange_RESTAPI_p_updatedProgramme_id_ec0169ed_fk_CyberRang"
            references public."CyberRange_RESTAPI_programme"
            deferrable initially deferred
);

alter table public."CyberRange_RESTAPI_programme"
    owner to asdf;

create index "CyberRange__id_b29a93_idx"
    on public."CyberRange_RESTAPI_programme" (id);

create index "CyberRange_RESTAPI_programme_name_609158bd_like"
    on public."CyberRange_RESTAPI_programme" (name varchar_pattern_ops);

create index "CyberRange_RESTAPI_programme_difficulty_id_6a85c60f"
    on public."CyberRange_RESTAPI_programme" (difficulty_id);

create index "CyberRange__id_c4600d_idx"
    on public."CyberRange_RESTAPI_scenario" (id);

create index "CyberRange_RESTAPI_scenario_difficulty_id_bebea7f4"
    on public."CyberRange_RESTAPI_scenario" (difficulty_id);

create table public."CyberRange_RESTAPI_scenario_bibliography"
(
    id              bigint generated by default as identity
        primary key,
    scenario_id     uuid not null
        constraint "CyberRange_RESTAPI_s_scenario_id_c62f6283_fk_CyberRang"
            references public."CyberRange_RESTAPI_scenario"
            deferrable initially deferred,
    bibliography_id uuid not null
        constraint "CyberRange_RESTAPI_s_bibliography_id_a1406ddf_fk_CyberRang"
            references public."CyberRange_RESTAPI_bibliography"
            deferrable initially deferred,
    constraint "CyberRange_RESTAPI_scena_scenario_id_bibliography_bbb44126_uniq"
        unique (scenario_id, bibliography_id)
);

alter table public."CyberRange_RESTAPI_scenario_bibliography"
    owner to asdf;

create index "CyberRange_RESTAPI_scenario_bibliography_scenario_id_c62f6283"
    on public."CyberRange_RESTAPI_scenario_bibliography" (scenario_id);

create index "CyberRange_RESTAPI_scenari_bibliography_id_a1406ddf"
    on public."CyberRange_RESTAPI_scenario_bibliography" (bibliography_id);

create table public."CyberRange_RESTAPI_scenario_cves"
(
    id          bigint generated by default as identity
        primary key,
    scenario_id uuid not null
        constraint "CyberRange_RESTAPI_s_scenario_id_2e4bde77_fk_CyberRang"
            references public."CyberRange_RESTAPI_scenario"
            deferrable initially deferred,
    cve_id      uuid not null
        constraint "CyberRange_RESTAPI_s_cve_id_ea0ea921_fk_CyberRang"
            references public."CyberRange_RESTAPI_cve"
            deferrable initially deferred,
    constraint "CyberRange_RESTAPI_scena_scenario_id_cve_id_c98494d8_uniq"
        unique (scenario_id, cve_id)
);

alter table public."CyberRange_RESTAPI_scenario_cves"
    owner to asdf;

create index "CyberRange_RESTAPI_scenario_cves_scenario_id_2e4bde77"
    on public."CyberRange_RESTAPI_scenario_cves" (scenario_id);

create index "CyberRange_RESTAPI_scenario_cves_cve_id_ea0ea921"
    on public."CyberRange_RESTAPI_scenario_cves" (cve_id);

create table public."CyberRange_RESTAPI_scenario_cwes"
(
    id          bigint generated by default as identity
        primary key,
    scenario_id uuid not null
        constraint "CyberRange_RESTAPI_s_scenario_id_63f33f95_fk_CyberRang"
            references public."CyberRange_RESTAPI_scenario"
            deferrable initially deferred,
    cwe_id      uuid not null
        constraint "CyberRange_RESTAPI_s_cwe_id_017925e9_fk_CyberRang"
            references public."CyberRange_RESTAPI_cwe"
            deferrable initially deferred,
    constraint "CyberRange_RESTAPI_scena_scenario_id_cwe_id_54fc14c2_uniq"
        unique (scenario_id, cwe_id)
);

alter table public."CyberRange_RESTAPI_scenario_cwes"
    owner to asdf;

create index "CyberRange_RESTAPI_scenario_cwes_scenario_id_63f33f95"
    on public."CyberRange_RESTAPI_scenario_cwes" (scenario_id);

create index "CyberRange_RESTAPI_scenario_cwes_cwe_id_017925e9"
    on public."CyberRange_RESTAPI_scenario_cwes" (cwe_id);

create table public."CyberRange_RESTAPI_scenario_mitreTactics"
(
    id             bigint generated by default as identity
        primary key,
    scenario_id    uuid not null
        constraint "CyberRange_RESTAPI_s_scenario_id_89f8bf56_fk_CyberRang"
            references public."CyberRange_RESTAPI_scenario"
            deferrable initially deferred,
    mitretactic_id uuid not null
        constraint "CyberRange_RESTAPI_s_mitretactic_id_3ce1c4ad_fk_CyberRang"
            references public."CyberRange_RESTAPI_mitretactic"
            deferrable initially deferred,
    constraint "CyberRange_RESTAPI_scena_scenario_id_mitretactic__0a90cf53_uniq"
        unique (scenario_id, mitretactic_id)
);

alter table public."CyberRange_RESTAPI_scenario_mitreTactics"
    owner to asdf;

create index "CyberRange_RESTAPI_scenario_mitreTactics_scenario_id_89f8bf56"
    on public."CyberRange_RESTAPI_scenario_mitreTactics" (scenario_id);

create index "CyberRange_RESTAPI_scenari_mitretactic_id_3ce1c4ad"
    on public."CyberRange_RESTAPI_scenario_mitreTactics" (mitretactic_id);

create table public."CyberRange_RESTAPI_scenario_mitreTechniques"
(
    id                bigint generated by default as identity
        primary key,
    scenario_id       uuid not null
        constraint "CyberRange_RESTAPI_s_scenario_id_c3580b82_fk_CyberRang"
            references public."CyberRange_RESTAPI_scenario"
            deferrable initially deferred,
    mitretechnique_id uuid not null
        constraint "CyberRange_RESTAPI_s_mitretechnique_id_17a95822_fk_CyberRang"
            references public."CyberRange_RESTAPI_mitretechnique"
            deferrable initially deferred,
    constraint "CyberRange_RESTAPI_scena_scenario_id_mitretechniq_4002d82c_uniq"
        unique (scenario_id, mitretechnique_id)
);

alter table public."CyberRange_RESTAPI_scenario_mitreTechniques"
    owner to asdf;

create index "CyberRange_RESTAPI_scenari_scenario_id_c3580b82"
    on public."CyberRange_RESTAPI_scenario_mitreTechniques" (scenario_id);

create index "CyberRange_RESTAPI_scenari_mitretechnique_id_17a95822"
    on public."CyberRange_RESTAPI_scenario_mitreTechniques" (mitretechnique_id);

create table public."CyberRange_RESTAPI_scenario_role"
(
    id          bigint generated by default as identity
        primary key,
    scenario_id uuid not null
        constraint "CyberRange_RESTAPI_s_scenario_id_fb26c473_fk_CyberRang"
            references public."CyberRange_RESTAPI_scenario"
            deferrable initially deferred,
    role_id     uuid not null
        constraint "CyberRange_RESTAPI_s_role_id_048121b4_fk_CyberRang"
            references public."CyberRange_RESTAPI_role"
            deferrable initially deferred,
    constraint "CyberRange_RESTAPI_scena_scenario_id_role_id_404faa95_uniq"
        unique (scenario_id, role_id)
);

alter table public."CyberRange_RESTAPI_scenario_role"
    owner to asdf;

create index "CyberRange_RESTAPI_scenario_role_scenario_id_fb26c473"
    on public."CyberRange_RESTAPI_scenario_role" (scenario_id);

create index "CyberRange_RESTAPI_scenario_role_role_id_048121b4"
    on public."CyberRange_RESTAPI_scenario_role" (role_id);

create table public."CyberRange_RESTAPI_state"
(
    id                     uuid        not null
        primary key,
    name                   varchar(20) not null,
    progress               integer     not null,
    layout                 varchar     not null,
    "isPreAssesment"       boolean     not null,
    "startState"           boolean     not null,
    "assessmentStartState" boolean     not null
);

alter table public."CyberRange_RESTAPI_state"
    owner to asdf;

create index "CyberRange__id_d173ff_idx"
    on public."CyberRange_RESTAPI_state" (id);

create table public."CyberRange_RESTAPI_state_onEnterEvent"
(
    id         bigint generated by default as identity
        primary key,
    state_id   uuid not null
        constraint "CyberRange_RESTAPI_s_state_id_8c78f5c6_fk_CyberRang"
            references public."CyberRange_RESTAPI_state"
            deferrable initially deferred,
    crevent_id uuid not null
        constraint "CyberRange_RESTAPI_s_crevent_id_05877c79_fk_CyberRang"
            references public."CyberRange_RESTAPI_crevent"
            deferrable initially deferred,
    constraint "CyberRange_RESTAPI_state_state_id_crevent_id_34d766b3_uniq"
        unique (state_id, crevent_id)
);

alter table public."CyberRange_RESTAPI_state_onEnterEvent"
    owner to asdf;

create index "CyberRange_RESTAPI_state_onEnterEvent_state_id_8c78f5c6"
    on public."CyberRange_RESTAPI_state_onEnterEvent" (state_id);

create index "CyberRange_RESTAPI_state_onEnterEvent_crevent_id_05877c79"
    on public."CyberRange_RESTAPI_state_onEnterEvent" (crevent_id);

create table public."CyberRange_RESTAPI_state_onExitEvent"
(
    id         bigint generated by default as identity
        primary key,
    state_id   uuid not null
        constraint "CyberRange_RESTAPI_s_state_id_411db74d_fk_CyberRang"
            references public."CyberRange_RESTAPI_state"
            deferrable initially deferred,
    crevent_id uuid not null
        constraint "CyberRange_RESTAPI_s_crevent_id_eeb5a20f_fk_CyberRang"
            references public."CyberRange_RESTAPI_crevent"
            deferrable initially deferred,
    constraint "CyberRange_RESTAPI_state_state_id_crevent_id_a432f34a_uniq"
        unique (state_id, crevent_id)
);

alter table public."CyberRange_RESTAPI_state_onExitEvent"
    owner to asdf;

create index "CyberRange_RESTAPI_state_onExitEvent_state_id_411db74d"
    on public."CyberRange_RESTAPI_state_onExitEvent" (state_id);

create index "CyberRange_RESTAPI_state_onExitEvent_crevent_id_eeb5a20f"
    on public."CyberRange_RESTAPI_state_onExitEvent" (crevent_id);

create table public."CyberRange_RESTAPI_usermetadata"
(
    id       uuid        not null
        primary key,
    username varchar(50) not null,
    "orgId"  varchar(50) not null,
    roles    jsonb       not null
);

alter table public."CyberRange_RESTAPI_usermetadata"
    owner to asdf;

create table public."CyberRange_RESTAPI_assignedprogramme"
(
    id                                      uuid                     not null
        primary key,
    "trainingScenariosCompletionPercentage" double precision         not null,
    "programmeFullyCompleted"               boolean                  not null,
    "programmeDueDate"                      timestamp with time zone,
    "totalTimeSpent"                        integer                  not null,
    "createdAt"                             timestamp with time zone not null,
    assigner_id                             uuid
        constraint "CyberRange_RESTAPI_a_assigner_id_b8fc2b54_fk_CyberRang"
            references public."CyberRange_RESTAPI_usermetadata"
            deferrable initially deferred,
    programme_id                            uuid                     not null
        constraint "CyberRange_RESTAPI_a_programme_id_d4765487_fk_CyberRang"
            references public."CyberRange_RESTAPI_programme"
            deferrable initially deferred
);

alter table public."CyberRange_RESTAPI_assignedprogramme"
    owner to asdf;

create index "CyberRange__id_12256d_idx"
    on public."CyberRange_RESTAPI_assignedprogramme" (id);

create index "CyberRange_RESTAPI_assignedprogramme_assigner_id_b8fc2b54"
    on public."CyberRange_RESTAPI_assignedprogramme" (assigner_id);

create index "CyberRange_RESTAPI_assignedprogramme_programme_id_d4765487"
    on public."CyberRange_RESTAPI_assignedprogramme" (programme_id);

create table public."CyberRange_RESTAPI_programmetrainer"
(
    id           uuid not null
        primary key,
    programme_id uuid not null
        constraint "CyberRange_RESTAPI_p_programme_id_7cdb20c7_fk_CyberRang"
            references public."CyberRange_RESTAPI_programme"
            deferrable initially deferred,
    trainer_id   uuid
        constraint "CyberRange_RESTAPI_p_trainer_id_2a48e7e8_fk_CyberRang"
            references public."CyberRange_RESTAPI_usermetadata"
            deferrable initially deferred
);

alter table public."CyberRange_RESTAPI_programmetrainer"
    owner to asdf;

create index "CyberRange__id_90ba29_idx"
    on public."CyberRange_RESTAPI_programmetrainer" (id);

create index "CyberRange_RESTAPI_programmetrainer_programme_id_7cdb20c7"
    on public."CyberRange_RESTAPI_programmetrainer" (programme_id);

create index "CyberRange_RESTAPI_programmetrainer_trainer_id_2a48e7e8"
    on public."CyberRange_RESTAPI_programmetrainer" (trainer_id);

create table public."CyberRange_RESTAPI_programmeuserreview"
(
    id               uuid not null
        primary key,
    programme_id     uuid
        constraint "CyberRange_RESTAPI_p_programme_id_3222e67a_fk_CyberRang"
            references public."CyberRange_RESTAPI_programme"
            deferrable initially deferred,
    review_id        uuid
        constraint "CyberRange_RESTAPI_p_review_id_1bc2cfcf_fk_CyberRang"
            references public."CyberRange_RESTAPI_review"
            deferrable initially deferred,
    user_metadata_id uuid
        constraint "CyberRange_RESTAPI_p_user_metadata_id_51a1a3e0_fk_CyberRang"
            references public."CyberRange_RESTAPI_usermetadata"
            deferrable initially deferred
);

alter table public."CyberRange_RESTAPI_programmeuserreview"
    owner to asdf;

create index "CyberRange_RESTAPI_programmeuserreview_programme_id_3222e67a"
    on public."CyberRange_RESTAPI_programmeuserreview" (programme_id);

create index "CyberRange_RESTAPI_programmeuserreview_review_id_1bc2cfcf"
    on public."CyberRange_RESTAPI_programmeuserreview" (review_id);

create index "CyberRange_RESTAPI_program_user_metadata_id_51a1a3e0"
    on public."CyberRange_RESTAPI_programmeuserreview" (user_metadata_id);

create index "CyberRange__id_67b4f1_idx"
    on public."CyberRange_RESTAPI_usermetadata" (id);

create table public."CyberRange_RESTAPI_usermetadata_assignedProgrammes"
(
    id                   bigint generated by default as identity
        primary key,
    usermetadata_id      uuid not null
        constraint "CyberRange_RESTAPI_u_usermetadata_id_274ab3eb_fk_CyberRang"
            references public."CyberRange_RESTAPI_usermetadata"
            deferrable initially deferred,
    assignedprogramme_id uuid not null
        constraint "CyberRange_RESTAPI_u_assignedprogramme_id_f4bbd4a8_fk_CyberRang"
            references public."CyberRange_RESTAPI_assignedprogramme"
            deferrable initially deferred,
    constraint "CyberRange_RESTAPI_userm_usermetadata_id_assigned_c5b7e789_uniq"
        unique (usermetadata_id, assignedprogramme_id)
);

alter table public."CyberRange_RESTAPI_usermetadata_assignedProgrammes"
    owner to asdf;

create index "CyberRange_RESTAPI_usermet_usermetadata_id_274ab3eb"
    on public."CyberRange_RESTAPI_usermetadata_assignedProgrammes" (usermetadata_id);

create index "CyberRange_RESTAPI_usermet_assignedprogramme_id_f4bbd4a8"
    on public."CyberRange_RESTAPI_usermetadata_assignedProgrammes" (assignedprogramme_id);

create table public."CyberRange_RESTAPI_usermetadata_assignedScenarios"
(
    id                  bigint generated by default as identity
        primary key,
    usermetadata_id     uuid not null
        constraint "CyberRange_RESTAPI_u_usermetadata_id_8a94e2bb_fk_CyberRang"
            references public."CyberRange_RESTAPI_usermetadata"
            deferrable initially deferred,
    assignedscenario_id uuid not null
        constraint "CyberRange_RESTAPI_u_assignedscenario_id_d014b79f_fk_CyberRang"
            references public."CyberRange_RESTAPI_assignedscenario"
            deferrable initially deferred,
    constraint "CyberRange_RESTAPI_userm_usermetadata_id_assigned_5179f769_uniq"
        unique (usermetadata_id, assignedscenario_id)
);

alter table public."CyberRange_RESTAPI_usermetadata_assignedScenarios"
    owner to asdf;

create index "CyberRange_RESTAPI_usermet_usermetadata_id_8a94e2bb"
    on public."CyberRange_RESTAPI_usermetadata_assignedScenarios" (usermetadata_id);

create index "CyberRange_RESTAPI_usermet_assignedscenario_id_d014b79f"
    on public."CyberRange_RESTAPI_usermetadata_assignedScenarios" (assignedscenario_id);

create table public."CyberRange_RESTAPI_usermetadata_createdProgrammes"
(
    id              bigint generated by default as identity
        primary key,
    usermetadata_id uuid not null
        constraint "CyberRange_RESTAPI_u_usermetadata_id_eb76c25b_fk_CyberRang"
            references public."CyberRange_RESTAPI_usermetadata"
            deferrable initially deferred,
    programme_id    uuid not null
        constraint "CyberRange_RESTAPI_u_programme_id_d15b495c_fk_CyberRang"
            references public."CyberRange_RESTAPI_programme"
            deferrable initially deferred,
    constraint "CyberRange_RESTAPI_userm_usermetadata_id_programm_044e2cd1_uniq"
        unique (usermetadata_id, programme_id)
);

alter table public."CyberRange_RESTAPI_usermetadata_createdProgrammes"
    owner to asdf;

create index "CyberRange_RESTAPI_usermet_usermetadata_id_eb76c25b"
    on public."CyberRange_RESTAPI_usermetadata_createdProgrammes" (usermetadata_id);

create index "CyberRange_RESTAPI_usermet_programme_id_d15b495c"
    on public."CyberRange_RESTAPI_usermetadata_createdProgrammes" (programme_id);

create table public."CyberRange_RESTAPI_usermetadata_createdScenarios"
(
    id              bigint generated by default as identity
        primary key,
    usermetadata_id uuid not null
        constraint "CyberRange_RESTAPI_u_usermetadata_id_2ae93fdd_fk_CyberRang"
            references public."CyberRange_RESTAPI_usermetadata"
            deferrable initially deferred,
    scenario_id     uuid not null
        constraint "CyberRange_RESTAPI_u_scenario_id_b80a072d_fk_CyberRang"
            references public."CyberRange_RESTAPI_scenario"
            deferrable initially deferred,
    constraint "CyberRange_RESTAPI_userm_usermetadata_id_scenario_154f0c10_uniq"
        unique (usermetadata_id, scenario_id)
);

alter table public."CyberRange_RESTAPI_usermetadata_createdScenarios"
    owner to asdf;

create index "CyberRange_RESTAPI_usermet_usermetadata_id_2ae93fdd"
    on public."CyberRange_RESTAPI_usermetadata_createdScenarios" (usermetadata_id);

create index "CyberRange_RESTAPI_usermet_scenario_id_b80a072d"
    on public."CyberRange_RESTAPI_usermetadata_createdScenarios" (scenario_id);

create table public."CyberRange_RESTAPI_usermetadata_reviews"
(
    id              bigint generated by default as identity
        primary key,
    usermetadata_id uuid not null
        constraint "CyberRange_RESTAPI_u_usermetadata_id_5c08cd8b_fk_CyberRang"
            references public."CyberRange_RESTAPI_usermetadata"
            deferrable initially deferred,
    review_id       uuid not null
        constraint "CyberRange_RESTAPI_u_review_id_5cd4054d_fk_CyberRang"
            references public."CyberRange_RESTAPI_review"
            deferrable initially deferred,
    constraint "CyberRange_RESTAPI_userm_usermetadata_id_review_i_7824c75c_uniq"
        unique (usermetadata_id, review_id)
);

alter table public."CyberRange_RESTAPI_usermetadata_reviews"
    owner to asdf;

create index "CyberRange_RESTAPI_usermet_usermetadata_id_5c08cd8b"
    on public."CyberRange_RESTAPI_usermetadata_reviews" (usermetadata_id);

create index "CyberRange_RESTAPI_usermetadata_reviews_review_id_5cd4054d"
    on public."CyberRange_RESTAPI_usermetadata_reviews" (review_id);

create table public."CyberRange_RESTAPI_usertrainingtime"
(
    id                       uuid    not null
        primary key,
    date                     date    not null,
    "totalTime"              integer not null,
    "programmeAssignment_id" uuid    not null
        constraint "CyberRange_RESTAPI_u_programmeAssignment__58b35d00_fk_CyberRang"
            references public."CyberRange_RESTAPI_assignedprogramme"
            deferrable initially deferred,
    user_id                  uuid    not null
        constraint "CyberRange_RESTAPI_u_user_id_1f56c7cc_fk_CyberRang"
            references public."CyberRange_RESTAPI_usermetadata"
            deferrable initially deferred,
    constraint "CyberRange_RESTAPI_usert_user_id_date_programmeAs_d53935f6_uniq"
        unique (user_id, date, "programmeAssignment_id")
);

alter table public."CyberRange_RESTAPI_usertrainingtime"
    owner to asdf;

create index "CyberRange__id_459d53_idx"
    on public."CyberRange_RESTAPI_usertrainingtime" (id, date);

create index "CyberRange_RESTAPI_usertra_programmeAssignment_id_58b35d00"
    on public."CyberRange_RESTAPI_usertrainingtime" ("programmeAssignment_id");

create index "CyberRange_RESTAPI_usertrainingtime_user_id_1f56c7cc"
    on public."CyberRange_RESTAPI_usertrainingtime" (user_id);

create table public."CyberRange_RESTAPI_transition"
(
    id                 uuid             not null
        primary key,
    name               varchar(100)     not null,
    probability        double precision not null,
    "sourceState_id"   uuid             not null
        constraint "CyberRange_RESTAPI_t_sourceState_id_7aa18af3_fk_CyberRang"
            references public."CyberRange_RESTAPI_state"
            deferrable initially deferred,
    "targetState_id"   uuid             not null
        constraint "CyberRange_RESTAPI_t_targetState_id_4c0dc26e_fk_CyberRang"
            references public."CyberRange_RESTAPI_state"
            deferrable initially deferred,
    "triggerAction_id" uuid             not null
        constraint "CyberRange_RESTAPI_t_triggerAction_id_fe4e4953_fk_CyberRang"
            references public."CyberRange_RESTAPI_crevent"
            deferrable initially deferred
);

alter table public."CyberRange_RESTAPI_transition"
    owner to asdf;

create index "CyberRange__id_9fb75c_idx"
    on public."CyberRange_RESTAPI_transition" (id);

create index "CyberRange_RESTAPI_transition_sourceState_id_7aa18af3"
    on public."CyberRange_RESTAPI_transition" ("sourceState_id");

create index "CyberRange_RESTAPI_transition_targetState_id_4c0dc26e"
    on public."CyberRange_RESTAPI_transition" ("targetState_id");

create index "CyberRange_RESTAPI_transition_triggerAction_id_fe4e4953"
    on public."CyberRange_RESTAPI_transition" ("triggerAction_id");

create table public."CyberRange_RESTAPI_trainingtype"
(
    id    uuid         not null
        primary key,
    value varchar(255) not null
);

alter table public."CyberRange_RESTAPI_trainingtype"
    owner to asdf;

create index "CyberRange__id_9cfefb_idx"
    on public."CyberRange_RESTAPI_trainingtype" (id);

create table public."CyberRange_RESTAPI_statemachine"
(
    id              uuid    not null
        primary key,
    "lazyLoad"      boolean not null,
    name            text    not null,
    "scenarioId_id" uuid    not null
        constraint "CyberRange_RESTAPI_s_scenarioId_id_9a7c2160_fk_CyberRang"
            references public."CyberRange_RESTAPI_scenario"
            deferrable initially deferred
);

alter table public."CyberRange_RESTAPI_statemachine"
    owner to asdf;

create table public."CyberRange_RESTAPI_instance"
(
    id                          uuid                     not null
        primary key,
    "currentPoints"             integer                  not null,
    "currentProgress"           integer                  not null,
    status                      varchar(20)              not null,
    "nextAssessmentNumber"      integer                  not null,
    "traineeId"                 varchar(36)              not null,
    "timeLeft"                  integer                  not null,
    "totalPoints"               integer                  not null,
    "reportFilePath"            varchar(255)             not null,
    "taskId"                    varchar(255),
    phase                       varchar(20)              not null,
    graph                       jsonb,
    history                     jsonb,
    "assessmentTimeFingerprint" timestamp with time zone,
    deterministic               varchar(20)              not null,
    "lastSessionStart"          timestamp with time zone,
    "lastSessionEnd"            timestamp with time zone,
    "totalTime"                 integer                  not null,
    "createdAt"                 timestamp with time zone not null,
    "FSMBlueprint_id"           uuid                     not null
        constraint "CyberRange_RESTAPI_i_FSMBlueprint_id_fc774d56_fk_CyberRang"
            references public."CyberRange_RESTAPI_statemachine"
            deferrable initially deferred,
    "lastVisitedState_id"       uuid
        constraint "CyberRange_RESTAPI_i_lastVisitedState_id_6eb4aa55_fk_CyberRang"
            references public."CyberRange_RESTAPI_state"
            deferrable initially deferred,
    "progressionInstance_id"    uuid
        constraint "CyberRange_RESTAPI_i_progressionInstance__9ff3c891_fk_CyberRang"
            references public."CyberRange_RESTAPI_progressioninstance"
            deferrable initially deferred,
    "scenarioId_id"             uuid                     not null
        constraint "CyberRange_RESTAPI_i_scenarioId_id_a9a9a9fb_fk_CyberRang"
            references public."CyberRange_RESTAPI_scenario"
            deferrable initially deferred
);

alter table public."CyberRange_RESTAPI_instance"
    owner to asdf;

create index "CyberRange__id_e2b43f_idx"
    on public."CyberRange_RESTAPI_instance" (id);

create index "CyberRange_RESTAPI_instance_FSMBlueprint_id_fc774d56"
    on public."CyberRange_RESTAPI_instance" ("FSMBlueprint_id");

create index "CyberRange_RESTAPI_instance_lastVisitedState_id_6eb4aa55"
    on public."CyberRange_RESTAPI_instance" ("lastVisitedState_id");

create index "CyberRange_RESTAPI_instance_progressionInstance_id_9ff3c891"
    on public."CyberRange_RESTAPI_instance" ("progressionInstance_id");

create index "CyberRange_RESTAPI_instance_scenarioId_id_a9a9a9fb"
    on public."CyberRange_RESTAPI_instance" ("scenarioId_id");

create table public."CyberRange_RESTAPI_usermetadata_createdInstances"
(
    id              bigint generated by default as identity
        primary key,
    usermetadata_id uuid not null
        constraint "CyberRange_RESTAPI_u_usermetadata_id_6dafba36_fk_CyberRang"
            references public."CyberRange_RESTAPI_usermetadata"
            deferrable initially deferred,
    instance_id     uuid not null
        constraint "CyberRange_RESTAPI_u_instance_id_c9babe36_fk_CyberRang"
            references public."CyberRange_RESTAPI_instance"
            deferrable initially deferred,
    constraint "CyberRange_RESTAPI_userm_usermetadata_id_instance_ef51cebd_uniq"
        unique (usermetadata_id, instance_id)
);

alter table public."CyberRange_RESTAPI_usermetadata_createdInstances"
    owner to asdf;

create index "CyberRange_RESTAPI_usermet_usermetadata_id_6dafba36"
    on public."CyberRange_RESTAPI_usermetadata_createdInstances" (usermetadata_id);

create index "CyberRange_RESTAPI_usermet_instance_id_c9babe36"
    on public."CyberRange_RESTAPI_usermetadata_createdInstances" (instance_id);

create index "CyberRange__id_40f043_idx"
    on public."CyberRange_RESTAPI_statemachine" (id);

create index "CyberRange_RESTAPI_statemachine_scenarioId_id_9a7c2160"
    on public."CyberRange_RESTAPI_statemachine" ("scenarioId_id");

create table public."CyberRange_RESTAPI_statemachine_events"
(
    id              bigint generated by default as identity
        primary key,
    statemachine_id uuid not null
        constraint "CyberRange_RESTAPI_s_statemachine_id_5c69cdd8_fk_CyberRang"
            references public."CyberRange_RESTAPI_statemachine"
            deferrable initially deferred,
    crevent_id      uuid not null
        constraint "CyberRange_RESTAPI_s_crevent_id_5402b570_fk_CyberRang"
            references public."CyberRange_RESTAPI_crevent"
            deferrable initially deferred,
    constraint "CyberRange_RESTAPI_state_statemachine_id_crevent__d7b1be4d_uniq"
        unique (statemachine_id, crevent_id)
);

alter table public."CyberRange_RESTAPI_statemachine_events"
    owner to asdf;

create index "CyberRange_RESTAPI_statemachine_events_statemachine_id_5c69cdd8"
    on public."CyberRange_RESTAPI_statemachine_events" (statemachine_id);

create index "CyberRange_RESTAPI_statemachine_events_crevent_id_5402b570"
    on public."CyberRange_RESTAPI_statemachine_events" (crevent_id);

create table public."CyberRange_RESTAPI_statemachine_states"
(
    id              bigint generated by default as identity
        primary key,
    statemachine_id uuid not null
        constraint "CyberRange_RESTAPI_s_statemachine_id_b1dde7ae_fk_CyberRang"
            references public."CyberRange_RESTAPI_statemachine"
            deferrable initially deferred,
    state_id        uuid not null
        constraint "CyberRange_RESTAPI_s_state_id_0e093edb_fk_CyberRang"
            references public."CyberRange_RESTAPI_state"
            deferrable initially deferred,
    constraint "CyberRange_RESTAPI_state_statemachine_id_state_id_147d3be4_uniq"
        unique (statemachine_id, state_id)
);

alter table public."CyberRange_RESTAPI_statemachine_states"
    owner to asdf;

create index "CyberRange_RESTAPI_statemachine_states_statemachine_id_b1dde7ae"
    on public."CyberRange_RESTAPI_statemachine_states" (statemachine_id);

create index "CyberRange_RESTAPI_statemachine_states_state_id_0e093edb"
    on public."CyberRange_RESTAPI_statemachine_states" (state_id);

create table public."CyberRange_RESTAPI_statemachine_transitions"
(
    id              bigint generated by default as identity
        primary key,
    statemachine_id uuid not null
        constraint "CyberRange_RESTAPI_s_statemachine_id_053f6edc_fk_CyberRang"
            references public."CyberRange_RESTAPI_statemachine"
            deferrable initially deferred,
    transition_id   uuid not null
        constraint "CyberRange_RESTAPI_s_transition_id_5f27e0fa_fk_CyberRang"
            references public."CyberRange_RESTAPI_transition"
            deferrable initially deferred,
    constraint "CyberRange_RESTAPI_state_statemachine_id_transiti_7c1097c9_uniq"
        unique (statemachine_id, transition_id)
);

alter table public."CyberRange_RESTAPI_statemachine_transitions"
    owner to asdf;

create index "CyberRange_RESTAPI_statema_statemachine_id_053f6edc"
    on public."CyberRange_RESTAPI_statemachine_transitions" (statemachine_id);

create index "CyberRange_RESTAPI_statema_transition_id_5f27e0fa"
    on public."CyberRange_RESTAPI_statemachine_transitions" (transition_id);

create table public."CyberRange_RESTAPI_standard"
(
    id          uuid         not null
        primary key,
    value       varchar(255) not null,
    description text         not null,
    url         varchar(200) not null,
    sdo         varchar(255) not null
);

alter table public."CyberRange_RESTAPI_standard"
    owner to asdf;

create index "CyberRange__id_68824a_idx"
    on public."CyberRange_RESTAPI_standard" (id);

create table public."CyberRange_RESTAPI_skill"
(
    id       uuid         not null
        primary key,
    value    varchar(255) not null,
    category varchar(255) not null
);

alter table public."CyberRange_RESTAPI_skill"
    owner to asdf;

create index "CyberRange__id_a0db4b_idx"
    on public."CyberRange_RESTAPI_skill" (id);

create table public."CyberRange_RESTAPI_scenariodependencies"
(
    id          uuid not null
        primary key,
    scenario_id uuid not null
        constraint "CyberRange_RESTAPI_s_scenario_id_6a187af7_fk_CyberRang"
            references public."CyberRange_RESTAPI_scenario"
            deferrable initially deferred
);

alter table public."CyberRange_RESTAPI_scenariodependencies"
    owner to asdf;

create index "CyberRange_RESTAPI_scenariodependencies_scenario_id_6a187af7"
    on public."CyberRange_RESTAPI_scenariodependencies" (scenario_id);

create table public."CyberRange_RESTAPI_scenariodependencies_dependencies"
(
    id                      bigint generated by default as identity
        primary key,
    scenariodependencies_id uuid not null
        constraint "CyberRange_RESTAPI_s_scenariodependencies_054abf9c_fk_CyberRang"
            references public."CyberRange_RESTAPI_scenariodependencies"
            deferrable initially deferred,
    scenario_id             uuid not null
        constraint "CyberRange_RESTAPI_s_scenario_id_25822298_fk_CyberRang"
            references public."CyberRange_RESTAPI_scenario"
            deferrable initially deferred,
    constraint "CyberRange_RESTAPI_scena_scenariodependencies_id__4fca4c0e_uniq"
        unique (scenariodependencies_id, scenario_id)
);

alter table public."CyberRange_RESTAPI_scenariodependencies_dependencies"
    owner to asdf;

create index "CyberRange_RESTAPI_scenari_scenariodependencies_id_054abf9c"
    on public."CyberRange_RESTAPI_scenariodependencies_dependencies" (scenariodependencies_id);

create index "CyberRange_RESTAPI_scenari_scenario_id_25822298"
    on public."CyberRange_RESTAPI_scenariodependencies_dependencies" (scenario_id);

create table public."CyberRange_RESTAPI_scenario_skills"
(
    id          bigint generated by default as identity
        primary key,
    scenario_id uuid not null
        constraint "CyberRange_RESTAPI_s_scenario_id_4336fbdf_fk_CyberRang"
            references public."CyberRange_RESTAPI_scenario"
            deferrable initially deferred,
    skill_id    uuid not null
        constraint "CyberRange_RESTAPI_s_skill_id_963faf7e_fk_CyberRang"
            references public."CyberRange_RESTAPI_skill"
            deferrable initially deferred,
    constraint "CyberRange_RESTAPI_scena_scenario_id_skill_id_a9e11d5c_uniq"
        unique (scenario_id, skill_id)
);

alter table public."CyberRange_RESTAPI_scenario_skills"
    owner to asdf;

create index "CyberRange_RESTAPI_scenario_skills_scenario_id_4336fbdf"
    on public."CyberRange_RESTAPI_scenario_skills" (scenario_id);

create index "CyberRange_RESTAPI_scenario_skills_skill_id_963faf7e"
    on public."CyberRange_RESTAPI_scenario_skills" (skill_id);

create table public."CyberRange_RESTAPI_scenario_standards"
(
    id          bigint generated by default as identity
        primary key,
    scenario_id uuid not null
        constraint "CyberRange_RESTAPI_s_scenario_id_8e109b29_fk_CyberRang"
            references public."CyberRange_RESTAPI_scenario"
            deferrable initially deferred,
    standard_id uuid not null
        constraint "CyberRange_RESTAPI_s_standard_id_cf86563a_fk_CyberRang"
            references public."CyberRange_RESTAPI_standard"
            deferrable initially deferred,
    constraint "CyberRange_RESTAPI_scena_scenario_id_standard_id_60f2f5b6_uniq"
        unique (scenario_id, standard_id)
);

alter table public."CyberRange_RESTAPI_scenario_standards"
    owner to asdf;

create index "CyberRange_RESTAPI_scenario_standards_scenario_id_8e109b29"
    on public."CyberRange_RESTAPI_scenario_standards" (scenario_id);

create index "CyberRange_RESTAPI_scenario_standards_standard_id_cf86563a"
    on public."CyberRange_RESTAPI_scenario_standards" (standard_id);

create table public."CyberRange_RESTAPI_scenario_trainingType"
(
    id              bigint generated by default as identity
        primary key,
    scenario_id     uuid not null
        constraint "CyberRange_RESTAPI_s_scenario_id_30054b06_fk_CyberRang"
            references public."CyberRange_RESTAPI_scenario"
            deferrable initially deferred,
    trainingtype_id uuid not null
        constraint "CyberRange_RESTAPI_s_trainingtype_id_9112c0e2_fk_CyberRang"
            references public."CyberRange_RESTAPI_trainingtype"
            deferrable initially deferred,
    constraint "CyberRange_RESTAPI_scena_scenario_id_trainingtype_9434aa9f_uniq"
        unique (scenario_id, trainingtype_id)
);

alter table public."CyberRange_RESTAPI_scenario_trainingType"
    owner to asdf;

create index "CyberRange_RESTAPI_scenario_trainingType_scenario_id_30054b06"
    on public."CyberRange_RESTAPI_scenario_trainingType" (scenario_id);

create index "CyberRange_RESTAPI_scenari_trainingtype_id_9112c0e2"
    on public."CyberRange_RESTAPI_scenario_trainingType" (trainingtype_id);

create table public."CyberRange_RESTAPI_progressioninstance_events"
(
    id                     bigint generated by default as identity
        primary key,
    progressioninstance_id uuid not null
        constraint "CyberRange_RESTAPI_p_progressioninstance__e9065d96_fk_CyberRang"
            references public."CyberRange_RESTAPI_progressioninstance"
            deferrable initially deferred,
    crevent_id             uuid not null
        constraint "CyberRange_RESTAPI_p_crevent_id_aec9640e_fk_CyberRang"
            references public."CyberRange_RESTAPI_crevent"
            deferrable initially deferred,
    constraint "CyberRange_RESTAPI_progr_progressioninstance_id_c_d6713e2a_uniq"
        unique (progressioninstance_id, crevent_id)
);

alter table public."CyberRange_RESTAPI_progressioninstance_events"
    owner to asdf;

create index "CyberRange_RESTAPI_progres_progressioninstance_id_e9065d96"
    on public."CyberRange_RESTAPI_progressioninstance_events" (progressioninstance_id);

create index "CyberRange_RESTAPI_progres_crevent_id_aec9640e"
    on public."CyberRange_RESTAPI_progressioninstance_events" (crevent_id);

create table public."CyberRange_RESTAPI_progressioninstance_states"
(
    id                     bigint generated by default as identity
        primary key,
    progressioninstance_id uuid not null
        constraint "CyberRange_RESTAPI_p_progressioninstance__640d71af_fk_CyberRang"
            references public."CyberRange_RESTAPI_progressioninstance"
            deferrable initially deferred,
    state_id               uuid not null
        constraint "CyberRange_RESTAPI_p_state_id_07685a5d_fk_CyberRang"
            references public."CyberRange_RESTAPI_state"
            deferrable initially deferred,
    constraint "CyberRange_RESTAPI_progr_progressioninstance_id_s_a97491e2_uniq"
        unique (progressioninstance_id, state_id)
);

alter table public."CyberRange_RESTAPI_progressioninstance_states"
    owner to asdf;

create index "CyberRange_RESTAPI_progres_progressioninstance_id_640d71af"
    on public."CyberRange_RESTAPI_progressioninstance_states" (progressioninstance_id);

create index "CyberRange_RESTAPI_progressioninstance_states_state_id_07685a5d"
    on public."CyberRange_RESTAPI_progressioninstance_states" (state_id);

create table public."CyberRange_RESTAPI_progressioninstance_transitions"
(
    id                     bigint generated by default as identity
        primary key,
    progressioninstance_id uuid not null
        constraint "CyberRange_RESTAPI_p_progressioninstance__f36c8002_fk_CyberRang"
            references public."CyberRange_RESTAPI_progressioninstance"
            deferrable initially deferred,
    transition_id          uuid not null
        constraint "CyberRange_RESTAPI_p_transition_id_1f375f57_fk_CyberRang"
            references public."CyberRange_RESTAPI_transition"
            deferrable initially deferred,
    constraint "CyberRange_RESTAPI_progr_progressioninstance_id_t_b6176138_uniq"
        unique (progressioninstance_id, transition_id)
);

alter table public."CyberRange_RESTAPI_progressioninstance_transitions"
    owner to asdf;

create index "CyberRange_RESTAPI_progres_progressioninstance_id_f36c8002"
    on public."CyberRange_RESTAPI_progressioninstance_transitions" (progressioninstance_id);

create index "CyberRange_RESTAPI_progres_transition_id_1f375f57"
    on public."CyberRange_RESTAPI_progressioninstance_transitions" (transition_id);

create table public."CyberRange_RESTAPI_programme_learningPlan"
(
    id                      bigint generated by default as identity
        primary key,
    programme_id            uuid not null
        constraint "CyberRange_RESTAPI_p_programme_id_7ff68d51_fk_CyberRang"
            references public."CyberRange_RESTAPI_programme"
            deferrable initially deferred,
    scenariodependencies_id uuid not null
        constraint "CyberRange_RESTAPI_p_scenariodependencies_13250514_fk_CyberRang"
            references public."CyberRange_RESTAPI_scenariodependencies"
            deferrable initially deferred,
    constraint "CyberRange_RESTAPI_progr_programme_id_scenariodep_52470504_uniq"
        unique (programme_id, scenariodependencies_id)
);

alter table public."CyberRange_RESTAPI_programme_learningPlan"
    owner to asdf;

create index "CyberRange_RESTAPI_programme_learningPlan_programme_id_7ff68d51"
    on public."CyberRange_RESTAPI_programme_learningPlan" (programme_id);

create index "CyberRange_RESTAPI_program_scenariodependencies_id_13250514"
    on public."CyberRange_RESTAPI_programme_learningPlan" (scenariodependencies_id);

create table public."CyberRange_RESTAPI_programme_prerequisiteProgrammes"
(
    id                bigint generated by default as identity
        primary key,
    from_programme_id uuid not null
        constraint "CyberRange_RESTAPI_p_from_programme_id_21c8eca4_fk_CyberRang"
            references public."CyberRange_RESTAPI_programme"
            deferrable initially deferred,
    to_programme_id   uuid not null
        constraint "CyberRange_RESTAPI_p_to_programme_id_7089af53_fk_CyberRang"
            references public."CyberRange_RESTAPI_programme"
            deferrable initially deferred,
    constraint "CyberRange_RESTAPI_progr_from_programme_id_to_pro_4398fb25_uniq"
        unique (from_programme_id, to_programme_id)
);

alter table public."CyberRange_RESTAPI_programme_prerequisiteProgrammes"
    owner to asdf;

create index "CyberRange_RESTAPI_program_from_programme_id_21c8eca4"
    on public."CyberRange_RESTAPI_programme_prerequisiteProgrammes" (from_programme_id);

create index "CyberRange_RESTAPI_program_to_programme_id_7089af53"
    on public."CyberRange_RESTAPI_programme_prerequisiteProgrammes" (to_programme_id);

create table public."CyberRange_RESTAPI_mitretechnique_tactics"
(
    id                bigint generated by default as identity
        primary key,
    mitretechnique_id uuid not null
        constraint "CyberRange_RESTAPI_m_mitretechnique_id_ff9d9fb8_fk_CyberRang"
            references public."CyberRange_RESTAPI_mitretechnique"
            deferrable initially deferred,
    mitretactic_id    uuid not null
        constraint "CyberRange_RESTAPI_m_mitretactic_id_9d7c28be_fk_CyberRang"
            references public."CyberRange_RESTAPI_mitretactic"
            deferrable initially deferred,
    constraint "CyberRange_RESTAPI_mitre_mitretechnique_id_mitret_a0161266_uniq"
        unique (mitretechnique_id, mitretactic_id)
);

alter table public."CyberRange_RESTAPI_mitretechnique_tactics"
    owner to asdf;

create index "CyberRange_RESTAPI_mitrete_mitretechnique_id_ff9d9fb8"
    on public."CyberRange_RESTAPI_mitretechnique_tactics" (mitretechnique_id);

create index "CyberRange_RESTAPI_mitrete_mitretactic_id_9d7c28be"
    on public."CyberRange_RESTAPI_mitretechnique_tactics" (mitretactic_id);

create table public."CyberRange_RESTAPI_assignedscenario_programmeTrainer"
(
    id                  bigint generated by default as identity
        primary key,
    assignedscenario_id uuid not null
        constraint "CyberRange_RESTAPI_a_assignedscenario_id_9f67a53c_fk_CyberRang"
            references public."CyberRange_RESTAPI_assignedscenario"
            deferrable initially deferred,
    programmetrainer_id uuid not null
        constraint "CyberRange_RESTAPI_a_programmetrainer_id_eb8ece9f_fk_CyberRang"
            references public."CyberRange_RESTAPI_programmetrainer"
            deferrable initially deferred,
    constraint "CyberRange_RESTAPI_assig_assignedscenario_id_prog_7fe8bc8d_uniq"
        unique (assignedscenario_id, programmetrainer_id)
);

alter table public."CyberRange_RESTAPI_assignedscenario_programmeTrainer"
    owner to asdf;

create index "CyberRange_RESTAPI_assigne_assignedscenario_id_9f67a53c"
    on public."CyberRange_RESTAPI_assignedscenario_programmeTrainer" (assignedscenario_id);

create index "CyberRange_RESTAPI_assigne_programmetrainer_id_eb8ece9f"
    on public."CyberRange_RESTAPI_assignedscenario_programmeTrainer" (programmetrainer_id);

create table public.django_content_type
(
    id        integer generated by default as identity
        primary key,
    app_label varchar(100) not null,
    model     varchar(100) not null,
    constraint django_content_type_app_label_model_76bd3d3b_uniq
        unique (app_label, model)
);

alter table public.django_content_type
    owner to asdf;

create table public.auth_permission
(
    id              integer generated by default as identity
        primary key,
    name            varchar(255) not null,
    content_type_id integer      not null
        constraint auth_permission_content_type_id_2f476e4b_fk_django_co
            references public.django_content_type
            deferrable initially deferred,
    codename        varchar(100) not null,
    constraint auth_permission_content_type_id_codename_01ab375a_uniq
        unique (content_type_id, codename)
);

alter table public.auth_permission
    owner to asdf;

create index auth_permission_content_type_id_2f476e4b
    on public.auth_permission (content_type_id);

create table public.auth_group
(
    id   integer generated by default as identity
        primary key,
    name varchar(150) not null
        unique
);

alter table public.auth_group
    owner to asdf;

create index auth_group_name_a6ea08ec_like
    on public.auth_group (name varchar_pattern_ops);

create table public.auth_group_permissions
(
    id            bigint generated by default as identity
        primary key,
    group_id      integer not null
        constraint auth_group_permissions_group_id_b120cbf9_fk_auth_group_id
            references public.auth_group
            deferrable initially deferred,
    permission_id integer not null
        constraint auth_group_permissio_permission_id_84c5c92e_fk_auth_perm
            references public.auth_permission
            deferrable initially deferred,
    constraint auth_group_permissions_group_id_permission_id_0cd325b0_uniq
        unique (group_id, permission_id)
);

alter table public.auth_group_permissions
    owner to asdf;

create index auth_group_permissions_group_id_b120cbf9
    on public.auth_group_permissions (group_id);

create index auth_group_permissions_permission_id_84c5c92e
    on public.auth_group_permissions (permission_id);

create table public.auth_user
(
    id           integer generated by default as identity
        primary key,
    password     varchar(128)             not null,
    last_login   timestamp with time zone,
    is_superuser boolean                  not null,
    username     varchar(150)             not null
        unique,
    first_name   varchar(150)             not null,
    last_name    varchar(150)             not null,
    email        varchar(254)             not null,
    is_staff     boolean                  not null,
    is_active    boolean                  not null,
    date_joined  timestamp with time zone not null
);

alter table public.auth_user
    owner to asdf;

create index auth_user_username_6821ab7c_like
    on public.auth_user (username varchar_pattern_ops);

create table public.auth_user_groups
(
    id       bigint generated by default as identity
        primary key,
    user_id  integer not null
        constraint auth_user_groups_user_id_6a12ed8b_fk_auth_user_id
            references public.auth_user
            deferrable initially deferred,
    group_id integer not null
        constraint auth_user_groups_group_id_97559544_fk_auth_group_id
            references public.auth_group
            deferrable initially deferred,
    constraint auth_user_groups_user_id_group_id_94350c0c_uniq
        unique (user_id, group_id)
);

alter table public.auth_user_groups
    owner to asdf;

create index auth_user_groups_user_id_6a12ed8b
    on public.auth_user_groups (user_id);

create index auth_user_groups_group_id_97559544
    on public.auth_user_groups (group_id);

create table public.auth_user_user_permissions
(
    id            bigint generated by default as identity
        primary key,
    user_id       integer not null
        constraint auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id
            references public.auth_user
            deferrable initially deferred,
    permission_id integer not null
        constraint auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm
            references public.auth_permission
            deferrable initially deferred,
    constraint auth_user_user_permissions_user_id_permission_id_14a6b632_uniq
        unique (user_id, permission_id)
);

alter table public.auth_user_user_permissions
    owner to asdf;

create index auth_user_user_permissions_user_id_a95ead1b
    on public.auth_user_user_permissions (user_id);

create index auth_user_user_permissions_permission_id_1fbb5f2c
    on public.auth_user_user_permissions (permission_id);

create table public.django_admin_log
(
    id              integer generated by default as identity
        primary key,
    action_time     timestamp with time zone not null,
    object_id       text,
    object_repr     varchar(200)             not null,
    action_flag     smallint                 not null
        constraint django_admin_log_action_flag_check
            check (action_flag >= 0),
    change_message  text                     not null,
    content_type_id integer
        constraint django_admin_log_content_type_id_c4bce8eb_fk_django_co
            references public.django_content_type
            deferrable initially deferred,
    user_id         integer                  not null
        constraint django_admin_log_user_id_c564eba6_fk_auth_user_id
            references public.auth_user
            deferrable initially deferred
);

alter table public.django_admin_log
    owner to asdf;

create index django_admin_log_content_type_id_c4bce8eb
    on public.django_admin_log (content_type_id);

create index django_admin_log_user_id_c564eba6
    on public.django_admin_log (user_id);

create table public.django_session
(
    session_key  varchar(40)              not null
        primary key,
    session_data text                     not null,
    expire_date  timestamp with time zone not null
);

alter table public.django_session
    owner to asdf;

create index django_session_session_key_c0390e0f_like
    on public.django_session (session_key varchar_pattern_ops);

create index django_session_expire_date_a5c62663
    on public.django_session (expire_date);

